// <auto-generated />
namespace DoctorsOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class doctorsinfo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctorsinfo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201502141249329_doctorsinfo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
